name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Extract tag name
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Echo version
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Bump package version
        run: |
          python3 helper/bump.py ${{ env.RELEASE_VERSION }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Bump package version" -a
      - name: Push changes - Bump package version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
      - name: Prepare release
        run: |
          python3 helper/clean.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Auto-remove roslint" -a
      - name: Push changes - New Release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true










          

